import React from "react";
import { Autocomplete, TextField, Chip } from "@mui/material";
import { useTranslation } from "react-i18next";
const UploadDocumentTopics = ({ value, onChange }) => {
  const { t } = useTranslation(); // Initialize translation hook
  const options = [
    "3D Printing",
    "Abstract Algebra",
    "Accounting",
    "Acoustics",
    "Advanced Calculus",
    "Advanced Mathematics",
    "Aerodynamics",
    "Aerospace Engineering",
    "Aerospace Systems",
    "African American Studies",
    "Agricultural Economics",
    "Agricultural Engineering",
    "Algebra",
    "American History",
    "Anatomy",
    "Ancient Civilizations",
    "Ancient Greek",
    "Ancient Languages",
    "Ancient Philosophy",
    "Animal Behavior",
    "Anthropology",
    "Anthropology of Religion",
    "Archaeology",
    "Architecture",
    "Art Education",
    "Art History",
    "Artificial Intelligence",
    "Artificial Life",
    "Artificial Neural Networks",
    "Asian Studies",
    "Astrobiology",
    "Astrophysics",
    "Astronomy",
    "Atmospheric Sciences",
    "Audiology",
    "Automation",
    "Behavioral Genetics",
    "Behavioral Neuroscience",
    "Behavioral Science",
    "Biblical Studies",
    "Bioengineering",
    "Bioethics",
    "Biochemical Engineering",
    "Biochemistry",
    "Biochemical Engineering",
    "Biochemistry",
    "Bioengineering",
    "Bioethics",
    "Biogeography",
    "Bioinformatics",
    "Bioinformatics Algorithms",
    "Biological Anthropology",
    "Biology",
    "Biomathematics",
    "Biomedical Engineering",
    "Biomedical Informatics",
    "Biophysics",
    "Biostatistics",
    "Biotechnology",
    "Botany",
    "Building Construction",
    "Business Administration",
    "Calculus",
    "Ceramic Engineering",
    "Chemical Biology",
    "Chemical Engineering",
    "Chemical Physics",
    "Chemistry",
    "Child Development",
    "Chinese Studies",
    "Civil Engineering",
    "Classics",
    "Climate Science",
    "Clinical Microbiology",
    "Clinical Psychology",
    "Cognitive Neuroscience",
    "Cognitive Science",
    "Communication Studies",
    "Comparative Literature",
    "Comparative Politics",
    "Computer Architecture",
    "Computer Graphics",
    "Computer Networks",
    "Computer Science",
    "Computer Security",
    "Computational Biology",
    "Computational Chemistry",
    "Computational Geometry",
    "Computational Linguistics",
    "Computational Neuroscience",
    "Computer Security",
    "Construction Management",
    "Control Systems",
    "Corrosion Engineering",
    "Counseling Psychology",
    "Creative Writing",
    "Criminal Justice",
    "Criminology",
    "Culinary Arts",
    "Cultural Anthropology",
    "Cultural Studies",
    "Cybernetics",
    "Cybersecurity",
    "Dairy Science",
    "Data Mining",
    "Data Science",
    "Decision Sciences",
    "Demography",
    "Dentistry",
    "Design",
    "Design Engineering",
    "Development Economics",
    "Developmental Biology",
    "Developmental Psychology",
    "Digital Art",
    "Digital Humanities",
    "Digital Media",
    "Digital Signal Processing",
    "Disaster Management",
    "Distributed Computing",
    "Earth Science",
    "Earthquake Engineering",
    "East Asian Studies",
    "Eastern Philosophy",
    "Economic History",
    "Economics",
    "Education",
    "Educational Leadership",
    "Educational Policy",
    "Electrical Engineering",
    "Electrical Power Engineering",
    "Electronic Engineering",
    "Electronics",
    "Endocrinology",
    "Energy Engineering",
    "Engineering Mechanics",
    "English Language",
    "English Literature",
    "Environmental Chemistry",
    "Environmental Economics",
    "Environmental Engineering",
    "Environmental Engineering Design",
    "Environmental Health",
    "Environmental Law",
    "Environmental Policy",
    "Environmental Psychology",
    "Environmental Science",
    "Environmental Sociology",
    "Environmental Toxicology",
    "Epidemiology",
    "Epidemiological Methods",
    "Epidemiological Surveillance",
    "Ethnomusicology",
    "European History",
    "Evolutionary Anthropology",
    "Evolutionary Biology",
    "Exercise Physiology",
    "Experimental Physics",
    "Family Medicine",
    "Family Studies",
    "Fashion Design",
    "Fiber Optics",
    "Film Production",
    "Film Studies",
    "Finance",
    "Financial Engineering",
    "Financial Mathematics",
    "Fine Arts",
    "Fire Protection Engineering",
    "Fire Science",
    "Fisheries Management",
    "Fisheries Science",
    "Fluid Dynamics",
    "Food Chemistry",
    "Food Engineering",
    "Food Packaging",
    "Food Safety",
    "Food Science",
    "Forensic Accounting",
    "Forensic Science",
    "Forest Management",
    "Forestry",
    "Freshwater Biology",
    "Fusion Energy",
    "Game Design",
    "Game Theory",
    "Gender and Politics",
    "Gender Studies",
    "General Relativity",
    "Genetic Engineering",
    "Genetics",
    "Geochemistry",
    "Geography",
    "Geology",
    "Geomatics",
    "Geophysics",
    "Geospatial Analysis",
    "Global Health",
    "Global Studies",
    "Government",
    "Graphic Design",
    "Health Communication",
    "Health Economics",
    "Health Informatics",
    "Health Policy",
    "Health Sciences",
    "Healthcare Management",
    "Hematology",
    "Heritage Conservation",
    "High Energy Physics",
    "Higher Education",
    "Hispanic Studies",
    "History",
    "History of Science",
    "Horticulture",
    "Hospitality Management",
    "Human Anatomy",
    "Human-Computer Interaction",
    "Human Development",
    "Human Evolution",
    "Human Geography",
    "Human Genetics",
    "Human Nutrition",
    "Human Physiology",
    "Human Resources",
    "Hydraulics",
    "Hydrology",
    "Immunogenetics",
    "Immunology",
    "Industrial Automation",
    "Industrial Design",
    "Industrial Engineering",
    "Industrial Hygiene",
    "Information Security",
    "Information Systems",
    "Information Technology",
    "Inorganic Chemistry",
    "Instructional Design",
    "Integrative Biology",
    "International Business",
    "International Development",
    "International Law",
    "International Relations",
    "Internet of Things",
    "Islamic Studies",
    "Japanese Studies",
    "Journalism",
    "Journalism Ethics",
    "Juvenile Justice",
    "K-12 Education",
    "Kinesiology",
    "Knowledge Management",
    "Landscape Architecture",
    "Landscape Ecology",
    "Latin American Studies",
    "Law",
    "Legal Studies",
    "Library Management",
    "Library Science",
    "Linguistics",
    "Literature",
    "Logic",
    "Machine Learning",
    "Management",
    "Marine Biology",
    "Marine Engineering",
    "Marketing",
    "Materials Chemistry",
    "Materials Science",
    "Mathematical Biology",
    "Mathematical Physics",
    "Mathematics",
    "Mechanical Design",
    "Mechanical Engineering",
    "Media Studies",
    "Medical Biophysics",
    "Medical Ethics",
    "Medical Technology",
    "Medicine",
    "Medieval Studies",
    "Membrane Biology",
    "Meteorology",
    "Microbiology",
    "Microelectronics",
    "Microeconomics",
    "Military History",
    "Molecular Biology",
    "Molecular Genetics",
    "Multicultural Education",
    "Multimedia Design",
    "Music Composition",
    "Music Education",
    "Music Performance",
    "Music Theory",
    "Mycology",
    "Nanomaterials",
    "Nanomedicine",
    "Nanotechnology",
    "Natural Resource Management",
    "Network Security",
    "Neuroscience",
    "Nuclear Engineering",
    "Nuclear Physics",
    "Nursing",
    "Nursing Education",
    "Nutrition",
    "Nutrition Science",
    "Occupational Health",
    "Occupational Therapy",
    "Ocean Engineering",
    "Oceanography",
    "Operations Management",
    "Operations Research",
    "Optometry",
    "Organic Chemistry",
    "Orthopedic Surgery",
    "Paleoclimatology",
    "Paleontology",
    "Parasitology",
    "Pathology",
    "Pediatrics",
    "Performance Studies",
    "Pharmacognosy",
    "Pharmacology",
    "Pharmacology and Toxicology",
    "Pharmacy",
    "Philosophy",
    "Philosophy of Language",
    "Philosophy of Science",
    "Photography",
    "Physical Chemistry",
    "Physical Education",
    "Physical Oceanography",
    "Physical Therapy",
    "Physician Assistant",
    "Physics",
    "Physics Education",
    "Physiology",
    "Planetary Science",
    "Plant Biology",
    "Plant Pathology",
    "Plant Science",
    "Political Economy",
    "Political Science",
    "Polymer Science",
    "Population Genetics",
    "Positive Psychology",
    "Pre-Law",
    "Pre-Medical",
    "Probability Theory",
    "Professional Writing",
    "Project Management",
    "Proteomics",
    "Psychiatric Nursing",
    "Psycholinguistics",
    "Psychometrics",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Public Policy",
    "Public Relations",
    "Quality Assurance",
    "Quantum Computing",
    "Quantum Mechanics",
    "Quantum Optics",
    "Radiation Biology",
    "Radiographic Imaging",
    "Radiology",
    "Real Analysis",
    "Real Estate",
    "Rehabilitation Counseling",
    "Religious Studies",
    "Remote Sensing",
    "Renewable Energy",
    "Rhetoric",
    "Risk Management",
    "Robotics",
    "Robotics and Automation",
    "Rural Sociology",
    "Science Education",
    "Science Policy",
    "Social Psychology",
    "Social Work",
    "Sociology",
    "Software Engineering",
    "Soil Science",
    "Space Science",
    "Spanish Literature",
    "Special Education",
    "Special Education Administration",
    "Speech Pathology",
    "Sports Management",
    "Sports Psychology",
    "Statistics",
    "Stem Cell Biology",
    "Structural Biology",
    "Structural Engineering",
    "Supply Chain Management",
    "Sustainability",
    "Sustainable Agriculture",
    "Systems Biology",
    "Systems Engineering",
    "Systems Neuroscience",
    "Tax Law",
    "Taxation",
    "Technical Writing",
    "Telecommunications",
    "Textile Engineering",
    "Textile Science",
    "Theater Arts",
    "Theology",
    "Theoretical Chemistry",
    "Theoretical Computer Science",
    "Theoretical Physics",
    "Tissue Engineering",
    "Tourism",
    "Tourism Management",
    "Toxicology",
    "Trauma Surgery",
    "Urban Economics",
    "Urban Planning",
    "Urban Studies",
    "Veterinary Medicine",
    "Veterinary Pathology",
    "Veterinary Science",
    "Virology",
    "Visual Arts",
    "Water Engineering",
    "Water Resources",
    "Web Development",
    "Wildlife Biology",
    "Wildlife Conservation",
    "Women in Engineering",
    "Women's Health",
    "Women's Literature",
    "Women's Studies",
    "World History",
    "Writing Studies",
    "Youth Development",
    "Zoological Studies",
    "Zoology",
  ]; // Add your options here later

  return (
    <Autocomplete
      multiple
      id="documentTopics"
      options={options}
      freeSolo
      renderTags={(value, getTagProps) =>
        value.map((option, index) => (
          <Chip variant="outlined" label={option} {...getTagProps({ index })} />
        ))
      }
      renderInput={(params) => (
        <TextField
          {...params}
          variant="outlined"
          label={t("document_topic")}
          placeholder="Add topics"
        />
      )}
      value={value}
      onChange={(event, newValue) => onChange(newValue)}
    />
  );
};

export default UploadDocumentTopics;
